### ISSUE TITLE
Can't sync till the end

### ISSUE THREAD

**Issue by arno-github** [nlgcoin/guldencoin#9]
With v1.3.1.0-unk-beta : can't succeed in sync'ing the linux wallet till the end. It stops at "2 hours from now" with this error :
QWidget::setMaximumSize: (separator/QWidget) The largest allowed size is (16777215,16777215)

**Comment by GeertJohan** [comment]
Hi @arno-github, thanks for reporting this in!

What distro are you running? What is your display resolution?

I'm assuming the error really pops up at the end of the sync and isn't an old error that was in the logs before that point. It looks like the sync itself is doing fine but displaying that it synced fine failed.. Somethine to do with widget size... Hence the question about your screen resolution..

**Comment by arno-github** [comment]
Hi
I'm using Ubuntu 14.04 LTS on a 1920x1080 display.
I restarted guldencoin-qt today and it synced totally...
Don't know if I have to close this issue or if you have to patch something before, to fix it.
Thanks for the answer and sorry for the "wrong" issue !

**Comment by GeertJohan** [comment]
Hi,
Its possible that at the yime of your first sync there simply wasnt a block for the past 2 hours, we're having some difficulties with the chain that we're working on and are almost solved. The Qt error/warning is probably unrelated to the sync problem.

No problem for opening this issue. It's always better to report problem than to ignore it. Normally I would've pursued the Qt error/warning but since we will be releasing a new wallet shortly that doesnt seem to be time-efficient, so I will close this issue. Cheers!
